#
# Find PAPI libraries
#

SET(PAPI_POSSIBLE_INCLUDE_PATHS
  /usr/include
  /usr/local/include
)

SET(PAPI_POSSIBLE_LIBRARY_PATHS
  /usr/lib
  /usr/local/lib
)

FIND_PATH(PAPI_INCLUDE_DIR NAMES papi.h PATHS ${PAPI_POSSIBLE_INCLUDE_PATHS})

FIND_LIBRARY(PAPI_LIBRARY NAMES libpapi.so PATHS ${PAPI_POSSIBLE_LIBRARY_PATHS})

#SET(PAPI_FOUND ON)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(PAPI DEFAULT_MSG PAPI_LIBRARY PAPI_INCLUDE_DIR)

MARK_AS_ADVANCED(
  PAPI_INCLUDE_DIR
  PAPI_LIBRARY
)

