MACRO(ADD_COMMON_MSVC_PROPS EXECUTABLE_NAME)
    IF(MSVC)        
        SET_TARGET_PROPERTIES(${EXECUTABLE_NAME}
            PROPERTIES
            LINK_FLAGS "/NODEFAULTLIB:libcmt /SUBSYSTEM:CONSOLE")
    ENDIF()
ENDMACRO()
