MACRO(ADD_COMMON_MSVC_PROPS EXECUTABLE_NAME)
    IF(MSVC)
        ADD_DEFINITIONS(/D_CRT_SECURE_NO_WARNINGS /DNOMINMAX /DWIN32_LEAN_AND_MEAN)

        SET_TARGET_PROPERTIES(${EXECUTABLE_NAME}
            PROPERTIES
            LINK_FLAGS "/NODEFAULTLIB:libcmt /SUBSYSTEM:CONSOLE")
    ENDIF(MSVC)
ENDMACRO()
